# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=50)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
                ('adquisicion', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
