# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('responsable', '0001_initial'),
        ('repuesto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='duracion',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='kilometraje',
            field=models.IntegerField(default=1212),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='repuesto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='responsable.Responsable'),
        ),
        migrations.AlterField(
            model_name='repuesto',
            name='adquisicion',
            field=models.CharField(choices=[(b'CASAKORE', b'CASAKORE'), (b'CULQUIMOTORS', b'CULQUIMOTORS'), (b'REP. MACAS', b'REP. MACAS'), (b'P Y M', b'P Y M'), (b'LLANTAS', b'LLANTAS')], max_length=50),
        ),
    ]
