# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuesto', '0002_auto_20171222_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='fechaCambio',
            field=models.DateField(default="2017-01-01"),
            preserve_default=False,
        ),
    ]
