# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-22 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuesto', '0003_repuesto_fechacambio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='fechaCambio',
            field=models.DateField(null=True),
        ),
    ]
