# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-23 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuesto', '0004_auto_20180122_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='duracion',
            field=models.IntegerField(null=True),
        ),
    ]
