# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-06 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuesto', '0005_auto_20180123_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='repuesto',
            name='orden',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
