# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuesto', '0006_repuesto_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
