# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-17 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repuesto', '0007_auto_20180316_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repuesto',
            name='adquisicion',
            field=models.CharField(choices=[(b'CASAKORE', b'CASAKORE'), (b'CULQUIMOTORS', b'CULQUIMOTORS'), (b'REP. MACAS', b'REP. MACAS'), (b'P Y M', b'P Y M'), (b'LLANTAS', b'LLANTAS'), (b'COMPRAS EN EFECTIVO DE CARRO', b'COMPRAS EN EFECTIVO DE CARRO'), (b'COMPRAS EN EFECTIVO DE MOTO', b'COMPRAS EN EFECTIVO DE MOTO')], max_length=50),
        ),
    ]
