# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 00:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0001_initial'),
        ('responsable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsable',
            name='vehiculo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo'),
        ),
    ]
